server = "https://registry.k8s.io"

[host."https://k8s.m.daocloud.io"]
  capabilities = ["pull", "resolve", "push"]

[host."registry.lank8s.cn"]
  capabilities = ["pull", "resolve", "push"]

[host."registry-k8s-io.mirrors.sjtug.sjtu.edu.cn"]
  capabilities = ["pull", "resolve", "push"]

[host."https://k8s.kubesre.xyz"]
  capabilities = ["pull", "resolve", "push"]

[host."registry.cn-hangzhou.aliyuncs.com/google_containers"]
capabilities = ["pull", "resolve", "push"]

[host."k8s.nju.edu.cn"]
  capabilities = ["pull", "resolve", "push"]
