server = "https://registry.jujucharms.com"
[host."https://jujucharms.kubesre.xyz"]
  capabilities = ["pull", "resolve", "push"]

[host."https://jujucharms.m.daocloud.io"]
  capabilities = ["pull", "resolve", "push"]
