apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-lvm-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-lvmpv
