#!/bin/bash

set -x

mkdir -p /home/kubernetes/postgres
cd /home/kubernetes/postgres

#helm install postgres oci://registry-1.docker.io/bitnamicharts/postgresql

VERSION="18.5.16"
# https://artifacthub.io/packages/helm/bitnami/postgresql?modal=install

#wget https://charts.bitnami.com/bitnami/postgresql-${VERSION}.tgz
helm repo add bitnami https://charts.bitnami.com/bitnami
helm pull bitnami/postgresql --version $VERSION

#helm pull ingress-nginx/ingress-nginx --untar --untar-dir /path/to/directory

tar -zxvf postgresql-${VERSION}.tgz

# 根据你的 kubectl get sc 输出，你有几个选择。
# 对于 PostgreSQL，您应该使用提供高可用性和数据持久性的 StorageClass，
# 例如由 OpenEBS Mayastor 支持的 StorageClass。
# 如果您没有可用的 Mayastor StorageClass，您可以临时使用 openebs-lvmpv 进行测试，但它缺少数据复制。
# 假设你有一个合适的，比如 openebs-mayastor。把它的sc名称添加到primary.persistence.storageClassName=<sc-name>参数里
kubectl get sc

cat > postgresql.conf <<EOF
# 核心网络与监听
listen_addresses = '*'  # 允许监听所有网络接口的连接

# SSL/TLS 核心配置
ssl = on
ssl_cert_file = '/opt/bitnami/postgresql/certs/tls.crt'
ssl_key_file = '/opt/bitnami/postgresql/certs/tls.key'
# 如果有自签 CA Pool，可以开启下面这行
# ssl_ca_file = '/opt/bitnami/postgresql/certs/ca.crt'

# 基础性能配置
wal_level = logical
max_replication_slots = 5
max_wal_senders = 5
timezone = 'Asia/Shanghai'
max_connections = 100
shared_buffers = 1GB
effective_cache_size = 3GB
maintenance_work_mem = 256MB
checkpoint_completion_target = 0.9
wal_buffers = 16MB
default_statistics_target = 100
random_page_cost = 1.1
effective_io_concurrency = 1000
work_mem = 4854kB
huge_pages = off
jit = off
wal_compression = on
min_wal_size = 1GB
max_wal_size = 4GB
EOF

cat > pg_hba.conf <<EOF
# TYPE  DATABASE        USER            ADDRESS                 METHOD
# 允许 Unix 域套接字连接（本地管理）
local   all             all                                     trust
# 允许本地回环非加密连接（用于 Kubernetes 健康检查）
host    all             all             127.0.0.1/32            trust
host    all             all             ::1/128                 trust
# 强制外部连接必须使用 SSL
hostssl all             all             0.0.0.0/0               scram-sha-256
EOF

kubectl delete configmap my-postgres-all-in-one-config -n postgres || true

kubectl create configmap my-postgres-all-in-one-config \
  --from-file=postgresql.conf \
  --from-file=pg_hba.conf \
  -n postgres

# 让 StatefulSet 的 Pod 滚动更新，重新读取新的 ConfigMap
# kubectl rollout restart statefulset postgres-postgresql -n postgres || true
# 或者在数据库容器执行
# SELECT pg_reload_conf();

# 自动生成TLS证书. pvc被删除重建时会重新生成证书
cat > pg_conf.yml <<EOF
global:
  postgresql:
    auth:
      username: "postgres"
      password: "msdnmm"
      database: "postgres"
    service:
      ports:
        postgresql: 5432

primary:
  service:
    type: LoadBalancer
  persistence:
    storageClass: "openebs-lvmpv"
  podSecurityContext:
    fsGroup: 999
  containerSecurityContext:
    runAsUser: 999

  # conf 和 hba配置从该Configmap读取
  existingConfigmap: "my-postgres-all-in-one-config"

  # postgres.conf 参数在这里添加和修改
  extendedConfiguration:
  # postgres_hba.conf 参数在这里添加和修改

  #pgHbaConfiguration: |-

tls:
  enabled: true
  autoGenerated: false # 关闭自生成，改用我们自己的证书
  certificatesSecret: "postgres-gateway-tls-secret" # 挂载上面 cert-manager 生成的密匙
  certFilename: "tls.crt"
  certKeyFilename: "tls.key"

volumePermissions:
  enabled: true
EOF

helm uninstall postgres -n postgres || true
kubectl delete pvc/data-postgres-postgresql-0 -n postgres
# kubectl rollout restart statefulset postgres-postgresql -n postgres
helm upgrade --install postgres ./postgresql \
  -n postgres \
  --create-namespace \
  -f pg_conf.yml
