# 观测与可视化组件 (Grafana, Jaeger, Kibana, Kafka-UI)
# 这些Web UI 或数据收集端，只有当你打开浏览器看监控、或者有流量时才需要资源。

apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: grafana-vpa
  namespace: observability
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grafana
  updatePolicy:
    updateMode: "InPlace"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: "30m"
          memory: "128Mi"
        maxAllowed:
          cpu: "300m"
          memory: "512Mi"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: jaeger-vpa
  namespace: observability
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jaeger
  updatePolicy:
    updateMode: "InPlace"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: "50m"
          memory: "128Mi"
        maxAllowed:
          cpu: "400m"
          memory: "512Mi"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: kafka-ui-vpa
  namespace: kafka
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kafbat-ui-kafka-ui
  updatePolicy:
    updateMode: "InPlace"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: "30m"
          memory: "128Mi"
        maxAllowed:
          cpu: "300m"
          memory: "512Mi"
