server = "https://docker.elastic.co"

[host."https://elastic.m.daocloud.io"]
  capabilities = ["pull", "resolve", "push"]

[host."https://elastic.kubesre.xyz"]
  capabilities = ["pull", "resolve", "push"]
