apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-root-ca
  namespace: example
spec:
  isCA: true # 声明它是 CA
  commonName: example-internal-root-ca
  secretName: example-root-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: global-ca-issuer
    kind: ClusterIssuer
