apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis
  labels:
    app: redis
spec:
  type: LoadBalancer
  ports:
    - name: redis-port
      port: 6379
      targetPort: 6379
      protocol: TCP
      nodePort: 32379
  selector:
    app: redis
